### ISSUE TITLE
Can't add tooltip to item without description

### ISSUE THREAD

**Issue by aaronhowser1** [aaronhowser1/Document-Your-Mod-Mod#5]
```json
{
  "conditions": [
    {
      "type": "dym:configuration_option",
      "name": "useIronChest",
      "value": true
    }
  ],
  "for": [
    {
      "type": "dym:item",
      "registry_name": "ironchest:wood_iron_chest_upgrade"
    }
  ],
  "tooltip": [
    "dym.tip.ironchest.wood_to_iron"
  ]
}
```
doesn't work, and displays in console
```java
[13:17:53] [Client thread/ERROR] [dym]: An error has occurred while attempting to parse JSON for file /assets/ironchest/dym/wood_to_iron_upgrade.json
[13:17:53] [Client thread/ERROR] [dym]: Error message: Missing documentation, expected to find a JsonArray
[13:17:53] [Client thread/ERROR] [dym]: Resource location where the issue happened: ironchest:wood_to_iron_upgrade
[13:17:53] [Client thread/ERROR] [dym]: The stacktrace will be printed to STDERR
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: com.google.gson.JsonSyntaxException: Missing documentation, expected to find a JsonArray
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraft.util.JsonUtils.getJsonArray(JsonUtils.java:342)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.aaronhowser1.documentmod.json.ModDocumentation.create(ModDocumentation.java:61)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.aaronhowser1.documentmod.json.DocumentationLoader.loadJsonFile(DocumentationLoader.java:127)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.aaronhowser1.documentmod.json.DocumentationLoader.lambda$loadModDocumentation$1(DocumentationLoader.java:88)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.aaronhowser1.documentmod.json.DocumentationLoader.loadModDocumentation(DocumentationLoader.java:88)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.aaronhowser1.documentmod.json.DocumentationLoader.loadFromJson(DocumentationLoader.java:52)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.aaronhowser1.documentmod.DocumentMod.postInit(DocumentMod.java:66)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraft.client.Minecraft.init(Minecraft.java:582)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:422)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[13:17:53] [Client thread/INFO] [STDERR]: [com.aaronhowser1.documentmod.json.DocumentationLoader:lambda$loadModDocumentation$1:88]: 	at GradleStart.main(GradleStart.java:25)
```

Adding
```java
  "documentation": [
  ],
```
didn't work, but
```java
  "documentation": [
""
  ],
```
did but just made an empty page.

**Comment by TheSilkMiner** [comment]
Is this supposed to work? Because I assumed that adding a documentation in JEI was the main feature and tooltips were just an addon.

E.g., in this case for iron chests, I assumed it would be something like

```json
{
  "conditions": [
    {
      "type": "dym:configuration_option",
      "name": "useIronChest",
      "value": true
    }
  ],
  "for": [
    {
      "type": "dym:item",
      "registry_name": "ironchest:wood_iron_chest_upgrade"
    }
  ],
  "documentation": [
    "dym.doc.ironchest.wood_to_iron"
  ],
  "tooltip": [
    "dym.tip.ironchest.wood_to_iron"
  ]
}
```

With the respective strings in the `lang` file:

```properties
dym.doc.ironchest.wood_to_iron=Used to upgrade a wooden Chest to an Iron Chest
dym.tip.ironchest.wood_to_iron=Upgrades Wood to Iron
```

Or something around this line.

**Comment by aaronhowser1** [comment]
That's fair, yeah
